default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: db/development_AskIt

test:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/test_AskIt.sqlite3

production:
  <<: *default
  database: db/production_AskIt
